CC = gcc
CFLAGS = -Wall -g  -pedantic -std=gnu99 -I/local/courses/csse2310/include
LIBS = -L/local/courses/csse2310/lib -lcsse2310a1

wordiply: uqwordiply.c
	$(CC) $(CFLAGS) $(LIBS) uqwordiply.c -o uqwordiply
